#!/bin/bash
export TENANCY_NS=yzpk9kei2fk7
export REGION_SHORT=sa-santiago-1
export REPO=ocir.${REGION_SHORT}.oci.oraclecloud.com/${TENANCY_NS}/apm-demo:v1

# login con user/tenancy y auth token
docker login ocir.${REGION_SHORT}.oci.oraclecloud.com -u "${TENANCY_NS}/juan.salamanca@oracle.com" -p "w_1b9C_WP{nnV49ITeX+"
