#!/bin/bash
# (c) 2024 Demo. MIT License
set -euo pipefail

# Load configuration
# =======================
source scripts/00-variables.sh

# Get Tenancy Namespace
# =======================
printf "INFO: Getting tenancy namespace...\n"
export TF_VAR_tenancy_namespace=$(oci os ns get --region $REGION --compartment-id $COMPARTMENT_ID --query "data" --raw-output)
printf "  -> %s\n" "$TF_VAR_tenancy_namespace"

# Get OKE Cluster OCID
# =======================
printf "INFO: Getting OKE Cluster OCID...\n"
export OKE_CLUSTER_OCID=$(oci ce cluster list --name "$OKE_CLUSTER_NAME" --compartment-id $COMPARTMENT_ID --query "data[0].id" --raw-output)
printf "  -> %s\n" "$OKE_CLUSTER_OCID"

# Get APM Domain
# =======================
printf "INFO: Getting APM Domain...\n"
APM_DOMAIN_ID=$(oci apm-control-plane apm-domain list --compartment-id $COMPARTMENT_ID --display-name "$APM_DOMAIN_NAME" --query "items[0].id" --raw-output)
printf "  -> %s\n" "$APM_DOMAIN_ID"
export APM_PRIVATE_DATA_KEY=$(oci apm-control-plane apm-domain get --apm-domain-id "$APM_DOMAIN_ID" --query "data-keys[?type=='PRIVATE'].value" --raw-output | jq -r '.[0]')
export APM_DATA_UPLOAD_ENDPOINT=$(oci apm-control-plane apm-domain get --apm-domain-id "$APM_DOMAIN_ID" --query "data-upload-endpoint" --raw-output)

# OCIR
# =======================
export OCIR_REPO_URL="$REGION.ocir.io/$TF_VAR_tenancy_namespace/$OCIR_REPO_NAME/$APP_IMAGE_NAME:$APP_IMAGE_TAG"

# Create .env file
# =======================
printf "INFO: Creating .env file...\n"
cat <<EOF > .env
# Auto-generated by 00b-export-variables.sh
export AUTH_TOKEN="$AUTH_TOKEN"
export COMPARTMENT_ID="$COMPARTMENT_ID"
export REGION="$REGION"
export VCN_ID="$VCN_ID"
export SUBNET_ID="$SUBNET_ID"
export IMAGE_ID="$IMAGE_ID"
export OKE_CLUSTER_NAME="$OKE_CLUSTER_NAME"
export KUBERNETES_VERSION="$KUBERNETES_VERSION"
export OKE_NODE_SHAPE="$OKE_NODE_SHAPE"
export OKE_AD="$OKE_AD"
export K8S_NAMESPACE="$K8S_NAMESPACE"
export OCIR_REPO_NAME="$OCIR_REPO_NAME"
export APP_IMAGE_NAME="$APP_IMAGE_NAME"
export APP_IMAGE_TAG="$APP_IMAGE_TAG"
export APM_DOMAIN_NAME="$APM_DOMAIN_NAME"
export TF_VAR_tenancy_namespace="$TF_VAR_tenancy_namespace"
export OKE_CLUSTER_OCID="$OKE_CLUSTER_OCID"
export APM_PRIVATE_DATA_KEY="$APM_PRIVATE_DATA_KEY"
export APM_DATA_UPLOAD_ENDPOINT="$APM_DATA_UPLOAD_ENDPOINT"
export OCIR_REPO_URL="$OCIR_REPO_URL"
EOF
printf "INFO: Done.\n"
